// Traduction française du moteur de présentation.
//
// ─────────────────────────────────────────────────────────────────────────
// POURQUOI CE FICHIER EXISTE
//
// `pptx-react-viewer` annonce le français dans son catalogue de langues,
// mais n'embarque que les chaînes anglaises : passer `defaultLocale="fr"`
// change le réglage sans changer un seul libellé. Le ruban s'affichait donc
// en anglais dans un OS entièrement français.
//
// Le moteur ne crée pas son instance i18next — il appelle `useTranslation()`
// et lit celle de l'OS. Il suffit donc d'enregistrer nos propres chaînes
// par-dessus les siennes.
//
// CE QUI EST TRADUIT, ET CE QUI NE L'EST PAS
//
// Le catalogue complet compte 3 356 entrées, dont l'essentiel est constitué
// de noms d'animations, de types de graphiques et de réglages fins qu'on
// n'atteint qu'en descendant loin dans les panneaux. Traduire ces 3 356
// entrées à la main serait long, et surtout fragile : une faute de frappe
// dans une clé passe inaperçue jusqu'au jour où quelqu'un ouvre le panneau
// concerné.
//
// Ce fichier couvre donc ce qu'on voit **en travaillant** : les onglets du
// ruban et leurs boutons, la barre d'outils, la barre d'état, le menu
// Fichier, le menu contextuel, le mode diaporama et le mode présentateur.
// Le reste reste en anglais et se traduira au fil de l'usage — le repli est
// **par clé**, pas par langue : une entrée absente d'ici prend simplement
// sa version anglaise, rien ne casse.
//
// Les clés sont plates et pointées (« pptx.ribbon.home ») : c'est la forme
// qu'attend la bibliothèque. Les `{{variables}}` doivent être conservées
// telles quelles, elles sont remplacées à l'affichage.
// ─────────────────────────────────────────────────────────────────────────

export const traductionsFr = {
  // ---- Barre d'état -------------------------------------------------------
  "pptx.statusBar.allSaved": "Tout est enregistré",
  "pptx.statusBar.unsavedChanges": "Modifications non enregistrées",
  "pptx.statusBar.slideOf": "Diapositive {{current}} sur {{total}}",
  "pptx.statusBar.noSlides": "Aucune diapositive",
  "pptx.statusBar.language": "Français",
  "pptx.statusBar.toggleNotes": "Afficher ou masquer les notes",
  "pptx.statusBar.normalView": "Mode Normal",
  "pptx.statusBar.slideSorter": "Trieuse de diapositives",
  "pptx.statusBar.slideShow": "Diaporama",
  "pptx.statusBar.zoomIn": "Zoom avant",
  "pptx.statusBar.zoomOut": "Zoom arrière",
  "pptx.statusBar.zoomToFit": "Ajuster à la fenêtre",

  // ---- Barre d'outils -----------------------------------------------------
  "pptx.toolbar.toggleSlidesPanel": "Afficher ou masquer les diapositives",
  "pptx.toolbar.undo": "Annuler",
  "pptx.toolbar.undoAction": "Annuler : {{action}}",
  "pptx.toolbar.redo": "Rétablir",
  "pptx.toolbar.redoAction": "Rétablir : {{action}}",
  "pptx.toolbar.comments": "Commentaires",
  "pptx.toolbar.toggleInspector": "Afficher ou masquer l'inspecteur",
  "pptx.toolbar.settingsShortcuts": "Réglages et raccourcis",
  "pptx.toolbar.settings": "Réglages",
  "pptx.toolbar.readOnly": "Lecture seule",
  "pptx.toolbar.save": "Enregistrer",

  // ---- Onglets du ruban ---------------------------------------------------
  "pptx.ribbon.tab.file": "Fichier",
  "pptx.ribbon.tab.home": "Accueil",
  "pptx.ribbon.tab.insert": "Insertion",
  "pptx.ribbon.tab.text": "Texte",
  "pptx.ribbon.tab.draw": "Dessin",
  "pptx.ribbon.tab.arrange": "Disposition",
  "pptx.ribbon.tab.design": "Création",
  "pptx.ribbon.tab.transitions": "Transitions",
  "pptx.ribbon.tab.animations": "Animations",
  "pptx.ribbon.tab.slideShow": "Diaporama",
  "pptx.ribbon.tab.record": "Enregistrement",
  "pptx.ribbon.tab.review": "Révision",
  "pptx.ribbon.tab.view": "Affichage",
  "pptx.ribbon.tab.help": "Aide",

  "pptx.ribbon.file": "Fichier",
  "pptx.ribbon.home": "Accueil",
  "pptx.ribbon.insert": "Insertion",
  "pptx.ribbon.text": "Texte",
  "pptx.ribbon.draw": "Dessin",
  "pptx.ribbon.arrange": "Disposition",
  "pptx.ribbon.design": "Création",
  "pptx.ribbon.transitions": "Transitions",
  "pptx.ribbon.animations": "Animations",
  "pptx.ribbon.slideShow": "Diaporama",
  "pptx.ribbon.review": "Révision",
  "pptx.ribbon.view": "Affichage",

  "pptx.ribbon.collapseRibbon": "Réduire le ruban",
  "pptx.ribbon.expandRibbon": "Développer le ruban",

  // ---- Ruban : groupes et commandes --------------------------------------
  "pptx.ribbon.clipboard": "Presse-papiers",
  "pptx.ribbon.painter": "Reproduire la mise en forme",
  "pptx.ribbon.slide": "Diapositive",
  "pptx.ribbon.slides": "Diapositives",
  "pptx.ribbon.newSlide": "Nouvelle diapositive",
  "pptx.ribbon.duplicateSlide": "Dupliquer la diapositive",
  "pptx.ribbon.font": "Police",
  "pptx.ribbon.paragraph": "Paragraphe",
  "pptx.ribbon.editing": "Édition",
  "pptx.ribbon.groupDrawing": "Dessin",
  "pptx.ribbon.groupShapeStyles": "Styles de forme",
  "pptx.ribbon.selectionPane": "Volet Sélection",

  "pptx.ribbon.fontFamily": "Police",
  "pptx.ribbon.fontSize": "Taille",
  "pptx.ribbon.growFont": "Agrandir la police",
  "pptx.ribbon.shrinkFont": "Réduire la police",
  "pptx.ribbon.clearFormatting": "Effacer la mise en forme",
  "pptx.ribbon.fontColour": "Couleur de police",
  "pptx.ribbon.fontColourValue": "Couleur de police {{color}}",
  "pptx.ribbon.customColour": "Couleur personnalisée…",
  "pptx.ribbon.textHighlightColour": "Couleur de surlignage",
  "pptx.ribbon.highlightColourValue": "Surlignage {{color}}",
  "pptx.ribbon.bulletList": "Liste à puces",
  "pptx.ribbon.justify": "Justifier",
  "pptx.ribbon.columns1": "1 colonne",
  "pptx.ribbon.columns2": "2 colonnes",
  "pptx.ribbon.columns3": "3 colonnes",
  "pptx.ribbon.textDirectionRotate90": "Rotation 90°",
  "pptx.ribbon.textDirectionRotate270": "Rotation 270°",
  "pptx.ribbon.textDirectionStacked": "Empilé",

  "pptx.ribbon.textBox": "Zone de texte",
  "pptx.ribbon.rect": "Rect.",
  "pptx.ribbon.rectangle": "Rectangle",
  "pptx.ribbon.ellipse": "Ellipse",
  "pptx.ribbon.line": "Trait",
  "pptx.ribbon.shapeStar5": "Étoile à 5 branches",
  "pptx.ribbon.image": "Image",
  "pptx.ribbon.insertImage": "Insérer une image",
  "pptx.ribbon.media": "Média",
  "pptx.ribbon.insertMedia": "Insérer un son ou une vidéo",
  "pptx.ribbon.table": "Tableau",
  "pptx.ribbon.insertTable": "Insérer un tableau 3 × 3",
  "pptx.ribbon.smartArt": "SmartArt",
  "pptx.ribbon.insertSmartArt": "Insérer un diagramme SmartArt",
  "pptx.ribbon.chartType": "Type de graphique",
  "pptx.ribbon.insertChart": "Insérer un graphique",
  "pptx.ribbon.equation": "Équation",
  "pptx.ribbon.insertEquation": "Insérer une équation (E = mc²)",
  "pptx.ribbon.link": "Lien",
  "pptx.ribbon.action": "Action",
  "pptx.ribbon.insertActionButton": "Insérer un bouton d'action",

  "pptx.ribbon.fwd": "Avant",
  "pptx.ribbon.bwd": "Arrière",
  "pptx.ribbon.alignLeft": "Aligner à gauche",
  "pptx.ribbon.alignCenter": "Centrer",
  "pptx.ribbon.alignRight": "Aligner à droite",
  "pptx.ribbon.alignTop": "Aligner en haut",
  "pptx.ribbon.alignMiddle": "Centrer verticalement",
  "pptx.ribbon.alignBottom": "Aligner en bas",
  "pptx.ribbon.distributeHorizontally": "Répartir horizontalement",
  "pptx.ribbon.distributeVertically": "Répartir verticalement",
  "pptx.ribbon.group": "Grouper",
  "pptx.ribbon.ungroup": "Dissocier",

  "pptx.ribbon.tool.select": "Sélectionner",
  "pptx.ribbon.tool.pen": "Stylo",
  "pptx.ribbon.tool.highlighter": "Surligneur",
  "pptx.ribbon.tool.eraser": "Gomme",
  "pptx.ribbon.tool.freeform": "Forme libre",
  "pptx.ribbon.colour": "Couleur",
  "pptx.ribbon.penColour": "Couleur du stylo",
  "pptx.ribbon.width": "Épaisseur",
  "pptx.ribbon.strokeWidth": "Épaisseur du trait",
  "pptx.ribbon.eyedropper": "Pipette",
  "pptx.ribbon.eyedropperTitle": "Prélever une couleur à l'écran",

  "pptx.ribbon.browseThemes": "Parcourir les thèmes",
  "pptx.ribbon.browseThemesTitle": "Parcourir et appliquer les thèmes fournis",
  "pptx.ribbon.theme.default": "Par défaut",
  "pptx.ribbon.theme.light": "Clair",
  "pptx.ribbon.theme.dark": "Sombre",
  "pptx.ribbon.editTheme": "Modifier le thème",
  "pptx.ribbon.slideSize": "Taille des diapositives",
  "pptx.ribbon.slideSizeTitle": "Taille des diapositives et propriétés du document",
  "pptx.ribbon.formatBackground": "Mise en forme de l'arrière-plan",
  "pptx.ribbon.formatBackgroundTitle":
    "Mettre en forme l'arrière-plan — ouvre l'inspecteur",

  "pptx.ribbon.transition.none": "Aucune",
  "pptx.ribbon.transition.fade": "Fondu",
  "pptx.ribbon.transition.push": "Poussée",
  "pptx.ribbon.transition.wipe": "Balayage",
  "pptx.ribbon.transition.split": "Séparation",
  "pptx.ribbon.transition.reveal": "Révélation",
  "pptx.ribbon.transition.cut": "Coupure",
  "pptx.ribbon.transition.cover": "Recouvrement",
  "pptx.ribbon.transition.uncover": "Découvrement",
  "pptx.ribbon.transitionTitle": "Transition {{name}}",
  "pptx.ribbon.preview": "Aperçu",
  "pptx.ribbon.previewTransition": "Aperçu de la transition",
  "pptx.ribbon.duration": "Durée :",
  "pptx.ribbon.transitionDurationTitle": "Durée de la transition, en secondes",
  "pptx.ribbon.applyTransitionToAll": "Appliquer à toutes les diapositives",
  "pptx.ribbon.advanceSlide": "Passer à la suivante",
  "pptx.ribbon.onMouseClick": "Au clic",
  "pptx.ribbon.afterDuration": "Après :",
  "pptx.ribbon.advanceAfterSeconds": "Passer automatiquement après ce délai",
  "pptx.ribbon.sound": "Son :",
  "pptx.ribbon.soundNone": "[Aucun son]",
  "pptx.ribbon.inspector": "Inspecteur",
  "pptx.ribbon.openInspectorTransitions":
    "Ouvrir l'inspecteur pour toutes les options de transition",
  "pptx.ribbon.removeAnimation": "Supprimer l'animation",

  "pptx.ribbon.slideShowOptions": "Options du diaporama",
  "pptx.ribbon.fromBeginning": "Depuis le début",
  "pptx.ribbon.presenterView": "Mode Présentateur",
  "pptx.ribbon.customShows": "Diaporamas personnalisés",
  "pptx.ribbon.customShowsButton": "Diaporamas personnalisés",
  "pptx.ribbon.show": "Afficher",
  "pptx.ribbon.setUpShow": "Configurer le diaporama",
  "pptx.ribbon.setUpShowTitle": "Régler le déroulement du diaporama",

  "pptx.ribbon.accessibility": "Accessibilité",
  "pptx.ribbon.accessibilityCheck": "Vérifier l'accessibilité",
  "pptx.ribbon.compare": "Comparer",
  "pptx.ribbon.compareTitle": "Comparer avec une autre présentation",
  "pptx.ribbon.shortcuts": "Raccourcis",
  "pptx.ribbon.shortcutsTitle": "Liste des raccourcis clavier",
  "pptx.ribbon.toggleGridOverlay": "Afficher ou masquer la grille",
  "pptx.ribbon.guides": "Repères",
  "pptx.ribbon.toggleGuides": "Afficher ou masquer les repères centraux",
  "pptx.ribbon.snapToGridTitle": "Aligner les éléments sur la grille",
  "pptx.ribbon.templatesOn": "Modèles activés",
  "pptx.ribbon.templatesOff": "Modèles désactivés",
  "pptx.ribbon.editTemplateTitle":
    "Modifier les éléments hérités du masque et de la disposition",

  "pptx.ribbon.open": "Ouvrir",
  "pptx.ribbon.openAnotherPresentation": "Ouvrir une autre présentation",
  "pptx.ribbon.savePptx": "Enregistrer (.pptx)",
  "pptx.ribbon.saveAsPptx": "Enregistrer au format .pptx",
  "pptx.ribbon.exportPng": "Exporter en PNG",
  "pptx.ribbon.exportPdf": "Exporter en PDF",
  "pptx.ribbon.exportVideo": "Exporter en vidéo",
  "pptx.ribbon.exportGif": "Exporter en GIF",
  "pptx.ribbon.exportGifTitle": "Exporter en GIF",
  "pptx.ribbon.exportCurrentSlidePng": "Exporter la diapositive en PNG",
  "pptx.ribbon.exportDeckPdf": "Exporter la présentation en PDF",
  "pptx.ribbon.exportWebmVideo": "Exporter en vidéo WebM",
  "pptx.ribbon.exporting": "Export en cours…",
  "pptx.ribbon.documentProperties": "Propriétés du document",
  "pptx.ribbon.properties": "Propriétés",
  "pptx.ribbon.signatures": "Signatures",
  "pptx.ribbon.replace": "Remplacer",
  "pptx.ribbon.protect": "Protéger",
  "pptx.ribbon.protectWithPassword": "Protéger par un mot de passe",
  "pptx.ribbon.embedFonts": "Incorporer les polices",
  "pptx.ribbon.manageEmbeddedFonts": "Gérer les polices incorporées",
  "pptx.ribbon.versionHistory": "Historique des versions",
  "pptx.ribbon.browseSavedVersions": "Parcourir les versions enregistrées",
  "pptx.ribbon.moreActions": "Autres actions",

  // ---- Menu Fichier -------------------------------------------------------
  "pptx.backstage.title": "Fichier",
  "pptx.backstage.back": "Retour à la présentation",
  "pptx.backstage.nav.home": "Accueil",
  "pptx.backstage.nav.new": "Nouveau",
  "pptx.backstage.nav.open": "Ouvrir",
  "pptx.backstage.nav.info": "Informations",
  "pptx.backstage.nav.save": "Enregistrer",
  "pptx.backstage.nav.saveAs": "Enregistrer sous",
  "pptx.backstage.nav.print": "Imprimer",
  "pptx.backstage.nav.share": "Partager",
  "pptx.backstage.nav.export": "Exporter",
  "pptx.backstage.nav.close": "Fermer",
  "pptx.backstage.nav.account": "Compte",
  "pptx.backstage.nav.options": "Options",
  "pptx.backstage.newHeading": "Nouveau",
  "pptx.backstage.searchPlaceholder": "Rechercher une présentation récente",
  "pptx.backstage.browseDevice": "Parcourir cet appareil",
  "pptx.backstage.recentHeading": "Récentes",
  "pptx.backstage.columnName": "Nom",
  "pptx.backstage.columnModified": "Modifié le",
  "pptx.backstage.columnSize": "Taille",
  "pptx.backstage.noRecent": "Aucune présentation récente.",
  "pptx.backstage.untitled": "Présentation sans titre.pptx",
  "pptx.backstage.justNow": "À l'instant",
  "pptx.backstage.minutesAgo": "il y a {{count}} min",
  "pptx.backstage.hoursAgo": "il y a {{count}} h",
  "pptx.backstage.template.blank.name": "Présentation vierge",
  "pptx.backstage.template.blank.description": "Partir d'une page blanche",
  "pptx.backstage.template.warm.name": "Accueil chaleureux",
  "pptx.backstage.template.warm.description": "Diapositives de titre affirmées",
  "pptx.backstage.template.geometry.name": "Géométrique",
  "pptx.backstage.template.geometry.description": "Formes modernes, contrastes forts",
  "pptx.backstage.template.mono.name": "Monochrome urbain",
  "pptx.backstage.template.mono.description": "Noir et blanc architectural",
  "pptx.backstage.template.earth.name": "Inspiration naturelle",
  "pptx.backstage.template.earth.description": "Palette calme et naturelle",
  "pptx.backstage.template.future.name": "Résolument moderne",
  "pptx.backstage.template.future.description": "Récit technologique épuré",

  // ---- Menu contextuel ----------------------------------------------------
  "pptx.contextMenu.ariaLabel": "Menu contextuel",
  "pptx.contextMenu.cut": "Couper",
  "pptx.contextMenu.copy": "Copier",
  "pptx.contextMenu.paste": "Coller",
  "pptx.contextMenu.duplicate": "Dupliquer",
  "pptx.contextMenu.delete": "Supprimer",
  "pptx.contextMenu.group": "Grouper",
  "pptx.contextMenu.ungroup": "Dissocier",
  "pptx.contextMenu.bringForward": "Avancer d'un plan",
  "pptx.contextMenu.bringToFront": "Mettre au premier plan",
  "pptx.contextMenu.sendBackward": "Reculer d'un plan",
  "pptx.contextMenu.sendToBack": "Mettre à l'arrière-plan",
  "pptx.contextMenu.addComment": "Ajouter un commentaire",
  "pptx.contextMenu.editHyperlink": "Modifier le lien",
  "pptx.contextMenu.insertRowAbove": "Insérer une ligne au-dessus",
  "pptx.contextMenu.insertRowBelow": "Insérer une ligne en dessous",
  "pptx.contextMenu.insertColumnLeft": "Insérer une colonne à gauche",
  "pptx.contextMenu.insertColumnRight": "Insérer une colonne à droite",
  "pptx.contextMenu.deleteRow": "Supprimer la ligne",
  "pptx.contextMenu.deleteColumn": "Supprimer la colonne",
  "pptx.contextMenu.mergeCells": "Fusionner à droite",
  "pptx.contextMenu.mergeSelectedCells": "Fusionner les cellules",
  "pptx.contextMenu.splitCell": "Fractionner la cellule",

  // ---- Diaporama ----------------------------------------------------------
  "pptx.slideShow.fromBeginning": "Depuis le début",
  "pptx.slideShow.fromBeginningTooltip": "Lancer le diaporama depuis le début",
  "pptx.slideShow.fromCurrent": "Depuis la diapositive active",
  "pptx.slideShow.fromCurrentTooltip":
    "Lancer le diaporama depuis la diapositive active",
  "pptx.slideShow.presenterView": "Mode Présentateur",
  "pptx.slideShow.presenterViewTooltip": "Mode Présentateur",
  "pptx.slideShow.rehearseTimings": "Vérifier le minutage",
  "pptx.slideShow.rehearseTimingsTooltip": "Vérifier le minutage",
  "pptx.slideShow.setUp": "Configurer le diaporama",
  "pptx.slideShow.setUpTooltip": "Configurer le diaporama",
  "pptx.slideShow.showOptions": "Options d'affichage",
  "pptx.slideShow.loopContinuously": "Boucler jusqu'à « Échap »",
  "pptx.slideShow.showWithoutNarration": "Sans narration",
  "pptx.slideShow.showWithoutAnimation": "Sans animation",
  "pptx.slideShow.showSubtitles": "Afficher les sous-titres",
  "pptx.slideShow.penColor": "Couleur du stylo",
  "pptx.slideShow.showSlides": "Diapositives à projeter",
  "pptx.slideShow.allSlides": "Toutes",
  "pptx.slideShow.fromTo": "De / à",
  "pptx.slideShow.from": "De",
  "pptx.slideShow.to": "À",
  "pptx.slideShow.customShow": "Diaporama personnalisé",

  // ---- Mode Présentateur --------------------------------------------------
  "pptx.presenter.presenterView": "Mode Présentateur",
  "pptx.presenter.speakerNotes": "Notes du présentateur",
  "pptx.presenter.nextSlidePreview": "Diapositive suivante",
  "pptx.presenter.nextSlide": "Diapositive suivante",
  "pptx.presenter.previousSlide": "Diapositive précédente",
  "pptx.presenter.next": "Suivante",
  "pptx.presenter.prev": "Précédente",
  "pptx.presenter.noNotes": "Aucune note pour cette diapositive",
  "pptx.presenter.noSlides": "Aucune diapositive",
  "pptx.presenter.endPresentation": "Terminer la présentation",
  "pptx.presenter.endOfPresentation": "Fin de la présentation",
  "pptx.presenter.currentTime": "Heure",
  "pptx.presenter.elapsed": "Temps écoulé",
  "pptx.presenter.timerProgress": "Progression du minuteur",
  "pptx.presenter.toggleTimer": "Interrompre ou reprendre le minuteur",
  "pptx.presenter.resetTimer": "Réinitialiser le minuteur",
  "pptx.presenter.timerTitle": "{{elapsed}} (segment {{segment}})",
  "pptx.presenter.slideLabel": "Diapositive {{current}} sur {{total}}",
  "pptx.presenter.seeAllSlides": "Voir toutes les diapositives",
  "pptx.presenter.slideNavigator": "Navigateur de diapositives",
  "pptx.presenter.closeNavigator": "Fermer",
  "pptx.presenter.screen": "Écran",
  "pptx.presenter.blackScreen": "Écran noir",
  "pptx.presenter.whiteScreen": "Écran blanc",
  "pptx.presenter.pointerArrow": "Flèche",
  "pptx.presenter.pointerPen": "Stylo",
  "pptx.presenter.pointerHighlighter": "Surligneur",
  "pptx.presenter.eraseAllInk": "Effacer toutes les annotations",
  "pptx.presenter.increaseFontSize": "Agrandir le texte",
  "pptx.presenter.decreaseFontSize": "Réduire le texte",
  "pptx.presenter.openAudienceWindow": "Ouvrir la fenêtre du public",
  "pptx.presenter.closeAudienceWindow": "Fermer la fenêtre du public",
  "pptx.presenter.swapDisplays": "Permuter les écrans",
  "pptx.presenter.zoomIn": "Zoom avant",
  "pptx.presenter.zoomOut": "Zoom arrière",
  "pptx.presenter.resetZoom": "Zoom à 100 %",

  // ---- Notes --------------------------------------------------------------
  "pptx.notes.title": "Notes",
  "pptx.notes.slideN": "Diapositive {{n}}",
  "pptx.notes.noSlide": "Aucune diapositive sélectionnée",
  "pptx.notes.clickToAddNotes": "Cliquez pour ajouter des notes",
  "pptx.notes.noNotes": "Aucune note",

  // ---- Affichage ----------------------------------------------------------
  "pptx.view.normal": "Normal",
  "pptx.view.presentationViews": "Modes d'affichage",
  "pptx.view.masterViews": "Modes Masque",
  "pptx.view.outlineView": "Mode Plan",
  "pptx.view.outlineViewTooltip": "Mode Plan : modifier la présentation comme du texte",
  "pptx.view.readingView": "Mode Lecture",
  "pptx.view.slideSorter": "Trieuse de diapositives",
  "pptx.view.slideSorterTooltip": "Trieuse de diapositives",
  "pptx.view.slideMasterTooltip": "Modifier les masques et les dispositions",
  "pptx.view.zoomToFit": "Ajuster à la fenêtre",
  "pptx.view.zoomToFitTooltip": "Ajuster la diapositive à la fenêtre",
  "pptx.view.guides": "Repères",
  "pptx.view.show": "Afficher",
  "pptx.view.snapToGrid": "Aligner sur la grille",
  "pptx.view.addHorizontalGuide": "Ajouter un repère horizontal",
  "pptx.view.addVerticalGuide": "Ajouter un repère vertical",
  "pptx.view.hGuide": "Repère H",
  "pptx.view.vGuide": "Repère V",
  "pptx.view.selection": "Sélection",
  "pptx.view.spell": "Orthographe",
  "pptx.view.toggleSpellCheck": "Activer ou désactiver la correction orthographique",
  "pptx.view.macros": "Macros",
  "pptx.view.eyedropperTooltip": "Pipette : prélever une couleur sur la diapositive",
  "pptx.view.templateEditingTooltip":
    "Activer ou désactiver la modification des éléments du masque",

  // ---- Révision -----------------------------------------------------------
  "pptx.review.spelling": "Orthographe",
  "pptx.review.proofing": "Vérification",
  "pptx.review.language": "Langue",
  "pptx.review.languageTooltip": "Choisir la langue de vérification",
  "pptx.review.toggleComments": "Afficher ou masquer les commentaires",
  "pptx.review.showComments": "Afficher les commentaires",
  "pptx.review.markAllRead": "Tout marquer comme lu",
  "pptx.review.toggleSpellCheck": "Activer ou désactiver la correction orthographique",
  "pptx.review.accessibility": "Accessibilité",
  "pptx.review.accessibilityCheck": "Vérifier l'accessibilité",
  "pptx.review.accessibilityCheckTooltip": "Rechercher les problèmes d'accessibilité",
  "pptx.review.translate": "Traduire",
  "pptx.review.translateTooltip": "Traduire le texte sélectionné",
  "pptx.review.thesaurus": "Dictionnaire des synonymes",
  "pptx.review.changes": "Modifications",
  "pptx.review.protect": "Protéger",
  "pptx.review.readOnly": "Toujours ouvrir en lecture seule",
  "pptx.review.restrictPermission": "Restreindre les autorisations",
  "pptx.review.hideInk": "Masquer les annotations",

  // ---- Fichier : formats --------------------------------------------------
  "pptx.file.saveAsPptx": "Enregistrer .pptx",
  "pptx.file.saveAsPptxTooltip": "Enregistrer comme présentation (.pptx)",
  "pptx.file.saveAsPpsx": "Enregistrer .ppsx",
  "pptx.file.saveAsPpsxTooltip": "Enregistrer comme diaporama (.ppsx)",
  "pptx.file.saveAsPptm": "Enregistrer .pptm",
  "pptx.file.saveAsPptmTooltip": "Enregistrer avec macros (.pptm)",
  "pptx.file.copyImage": "Copier l'image",
  "pptx.file.copyImageTooltip": "Copier la diapositive comme image",
  "pptx.file.package": "Package",
  "pptx.file.packageTooltip": "Créer un package à partager",
  "pptx.file.fonts": "Polices",
  "pptx.file.video": "Vidéo",
  "pptx.file.audio": "Son",

  // ---- Barre d'édition ----------------------------------------------------
  "pptx.editorToolbar.ariaLabel": "Barre d'outils d'édition",
  "pptx.editorToolbar.insert": "Insertion",
  "pptx.editorToolbar.insertTextBox": "Insérer une zone de texte",
  "pptx.editorToolbar.insertRectangle": "Insérer un rectangle",
  "pptx.editorToolbar.insertEllipse": "Insérer une ellipse",
  "pptx.editorToolbar.insertLine": "Insérer un trait",
  "pptx.editorToolbar.arrange": "Disposition",
  "pptx.editorToolbar.align": "Aligner",
  "pptx.editorToolbar.alignLeft": "Aligner à gauche",
  "pptx.editorToolbar.alignCenter": "Centrer",
  "pptx.editorToolbar.alignRight": "Aligner à droite",
  "pptx.editorToolbar.alignTop": "Aligner en haut",
  "pptx.editorToolbar.alignMiddle": "Centrer verticalement",
  "pptx.editorToolbar.alignBottom": "Aligner en bas",
  "pptx.editorToolbar.addShape": "Ajouter : {{shape}}",
  "pptx.editorToolbar.addTextBox": "Ajouter une zone de texte",
  "pptx.editorToolbar.history": "Historique",
  "pptx.editorToolbar.resetZoom": "Zoom par défaut",
  "pptx.editorToolbar.resetZoomTo100": "Zoom à 100 %",
  "pptx.editorToolbar.shapeEllipse": "Ellipse",
  "pptx.editorToolbar.shapeRectangle": "Rectangle",
  "pptx.editorToolbar.shapeRoundedRectangle": "Rectangle arrondi",
  "pptx.editorToolbar.shapeTriangle": "Triangle",
  "pptx.editorToolbar.shapeCallout": "Bulle",

  // ---- Zoom ---------------------------------------------------------------
  "pptx.zoom.slideZoom": "Zoom sur une diapositive",
  "pptx.zoom.sectionZoom": "Zoom sur une section",
  "pptx.zoom.summaryZoom": "Zoom de résumé",
  "pptx.zoom.slideNumber": "Diapositive {{number}}",
  "pptx.zoom.slidePreviewAlt": "Aperçu de la diapositive {{number}}",
  "pptx.zoom.ariaLabel": "Zoomer sur la diapositive {{number}}",

  // ---- Visionneuse --------------------------------------------------------
  "pptx.viewer.loading": "Chargement de la présentation…",
  "pptx.viewer.loadError": "La présentation n'a pas pu être ouverte.",
  "pptx.viewer.encrypted":
    "Cette présentation est protégée par un mot de passe et ne peut pas être ouverte.",
  "pptx.viewer.slide": "Diapositive",
  "pptx.viewer.background": "Arrière-plan",
  "pptx.viewer.speakerNotesPlaceholder": "Cliquez pour ajouter des notes",
  "pptx.viewer.digitalSignatures": "Signatures numériques",
  "pptx.viewer.elementProperties": "Propriétés de l'élément",
  "pptx.viewer.slideProperties": "Propriétés de la diapositive",
  "pptx.viewer.slideEditorAria": "Éditeur de diapositive",

  // ---- Divers -------------------------------------------------------------
  "pptx.common.apply": "Appliquer",
  "pptx.common.loading": "Chargement…",
  "pptx.common.remove": "Supprimer",

  // ---- Accueil : diapositives --------------------------------------------
  "pptx.home.newSlide": "Nouvelle diapositive",
  "pptx.home.slideTemplates": "Modèles de diapositive",
  "pptx.home.chooseLayout": "Choisir une disposition",

  "pptx.sections.slides": "Diapositives",
  "pptx.sections.sectionButtonLabel": "Section",
  "pptx.sections.addSlide": "Ajouter une diapositive",
  "pptx.sections.addSection": "Ajouter une section",
  "pptx.sections.addBefore": "Ajouter une section avant",
  "pptx.sections.addAfter": "Ajouter une section après",
  "pptx.sections.defaultName": "Section sans titre",
  "pptx.sections.rename": "Renommer",
  "pptx.sections.delete": "Supprimer",
  "pptx.sections.moveUp": "Monter",
  "pptx.sections.moveDown": "Descendre",
  "pptx.sections.resetSlideTitle": "Réinitialiser la diapositive",
  "pptx.sections.collapsePane": "Réduire le volet",

  // ---- Casse et espacement des caractères --------------------------------
  "pptx.text.title": "Texte",
  "pptx.text.changeCase": "Modifier la casse",
  "pptx.text.changeCaseSentence": "Majuscule en début de phrase.",
  "pptx.text.changeCaseLower": "minuscules",
  "pptx.text.changeCaseUpper": "MAJUSCULES",
  "pptx.text.changeCaseCapitalize": "Majuscule À Chaque Mot",
  "pptx.text.changeCaseToggle": "iNVERSER lA cASSE",
  "pptx.text.characterSpacing": "Espacement des caractères",
  "pptx.text.characterSpacingVeryTight": "Très resserré",
  "pptx.text.characterSpacingTight": "Resserré",
  "pptx.text.characterSpacingNormal": "Normal",
  "pptx.text.characterSpacingLoose": "Étendu",
  "pptx.text.characterSpacingVeryLoose": "Très étendu",

  // ---- Masques ------------------------------------------------------------
  "pptx.master.title": "Masque des diapositives",
  "pptx.master.master": "Masque",
  "pptx.master.layout": "Disposition",
  "pptx.master.handoutMasterTitle": "Masque du document",
  "pptx.master.notesMasterTitle": "Masque des notes",
  "pptx.master.noMasters": "Aucun masque",
  "pptx.master.noSlideMasters": "Aucun masque de diapositive",
  "pptx.master.noHandoutMaster": "Aucun masque de document",
  "pptx.master.noNotesMaster": "Aucun masque de notes",
  "pptx.master.noPlaceholders": "Aucune réserve",
  "pptx.master.handoutPlaceholders": "Réserves",
  "pptx.master.notesMasterPlaceholders": "Réserves",
  "pptx.master.handoutBackground": "Arrière-plan",
  "pptx.master.notesMasterBackground": "Arrière-plan",
  "pptx.master.handoutSlidesPerPage": "Diapositives par page",
  "pptx.master.handoutSlideSlot": "Diapositive {{number}}",
  "pptx.master.notesMasterBody": "Corps",
  "pptx.master.notesMasterDate": "Date",
  "pptx.master.notesMasterFooter": "Pied de page",
  "pptx.master.notesMasterHeader": "En-tête",
  "pptx.master.notesMasterPageNumber": "Numéro de page",
  "pptx.master.notesMasterSlideImage": "Image de la diapositive",
  "pptx.master.collapseMasterPane": "Réduire le volet",
  "pptx.masterView.handoutMasterTitle": "Masque du document",
  "pptx.masterView.notesMasterTitle": "Masque des notes",

  // ---- Règles, grille, repères -------------------------------------------
  "pptx.ruler.rulers": "Règles",
  "pptx.ruler.toggleRulers": "Afficher ou masquer les règles",
  "pptx.grid.grid": "Grille",
  "pptx.grid.toggleGrid": "Afficher ou masquer la grille",
  "pptx.grid.snapToGrid": "Aligner sur la grille",
  "pptx.grid.snapToShape": "Aligner sur les formes",
  "pptx.settings.snapToGrid": "Aligner sur la grille",

  // ---- Trieuse de diapositives -------------------------------------------
  "pptx.slideSorter.title": "Trieuse de diapositives",
  "pptx.slideSorter.selectedCount": "{{count}} sélectionnée(s)",
  "pptx.slideSorter.slideCount": "{{count}} diapositive(s)",
  "pptx.slideSorter.close": "Fermer",
  "pptx.slideSorter.zoom": "Zoom",
  "pptx.slideSorter.zoomIn": "Zoom avant",
  "pptx.slideSorter.zoomOut": "Zoom arrière",
  "pptx.slideSorter.hidden": "Masquée",
  "pptx.slideSorter.contextMenu.copy": "Copier",
  "pptx.slideSorter.contextMenu.paste": "Coller",
  "pptx.slideSorter.contextMenu.duplicate": "Dupliquer",
  "pptx.slideSorter.contextMenu.delete": "Supprimer",
  "pptx.slideSorter.contextMenu.hideSlides": "Masquer les diapositives",
  "pptx.slideSorter.contextMenu.showSlides": "Afficher les diapositives",

  // ---- Volet Texte --------------------------------------------------------
  "pptx.textPanel.title": "Texte",
  "pptx.textPanel.font": "Police",
  "pptx.textPanel.size": "Taille (pt)",
  "pptx.textPanel.color": "Couleur",
  "pptx.textPanel.style": "Style",
  "pptx.textPanel.default": "Par défaut",
  "pptx.textPanel.bold": "Gras",
  "pptx.textPanel.italic": "Italique",
  "pptx.textPanel.underline": "Souligné",
  "pptx.textPanel.strikethrough": "Barré",
  "pptx.textPanel.horizontalAlign": "Alignement horizontal",
  "pptx.textPanel.verticalAlign": "Alignement vertical",
  "pptx.textPanel.alignLeft": "Gauche",
  "pptx.textPanel.alignCenter": "Centre",
  "pptx.textPanel.alignRight": "Droite",
  "pptx.textPanel.alignJustify": "Justifié",
  "pptx.textPanel.valignTop": "Haut",
  "pptx.textPanel.valignMiddle": "Milieu",
  "pptx.textPanel.valignBottom": "Bas",
  "pptx.textPanel.noTextProperties": "Cet élément n'a pas de propriétés de texte.",

  // ---- Disposition (groupe) ----------------------------------------------
  "pptx.arrange.groupLabel": "Disposition",
  "pptx.arrange.cut": "Couper",
  "pptx.arrange.copy": "Copier",
  "pptx.arrange.paste": "Coller",
  "pptx.arrange.format": "Format",
  "pptx.arrange.formatPainter": "Reproduire la mise en forme",
  "pptx.arrange.flipHorizontally": "Retourner horizontalement",

  // ---- Diaporama : lancement ---------------------------------------------
  "pptx.slideShow.present": "Présenter",
  "pptx.slideShow.start": "Lancer le diaporama",
  "pptx.slideShow.rehearseCoach": "Répéter avec le coach",
  "pptx.toolbar.present": "Présenter",
  "pptx.customShows.addShow": "+ Diaporama",

  "pptx.common.reset": "Réinitialiser",

  // ---- Mêmes libellés, autres clés ---------------------------------------
  //
  // Un même mot anglais apparaît souvent sous plusieurs clés — « Reset »
  // en a cinq, « Text » six. Traduire une seule d'entre elles laisse les
  // autres en anglais à l'écran, sans qu'on sache laquelle est réellement
  // affichée. Ce bloc couvre toutes les clés qui portent un libellé déjà
  // traduit plus haut ; il est généré par balayage du catalogue anglais,
  // pas écrit à la main.
  "pptx.documentProperties.statistics.slides": "Diapositives",
  "pptx.animations.reset": "Réinitialiser",
  "pptx.themeEditor.reset": "Réinitialiser",
  "pptx.imageAdjustments.reset": "Réinitialiser",
  "pptx.options.quickAccess.reset": "Réinitialiser",
  "pptx.selectionPane.show": "Afficher",
  "pptx.password.show": "Afficher",
  "pptx.security.show": "Afficher",
  "pptx.mobileBar.present": "Présenter",
  "pptx.mobileMenu.present": "Présenter",
  "pptx.shortcuts.group.editing": "Édition",
  "pptx.inspector.arrange": "Disposition",
  "pptx.smartArt.text": "Texte",
  "pptx.inspector.text": "Texte",
  "pptx.table.color": "Texte",
  "pptx.documentProperties.custom.typeText": "Texte",
  "pptx.undoAction.paste": "Coller",
  "pptx.arrange.delete": "Supprimer",
  "pptx.comments.delete": "Supprimer",
  "pptx.customShows.delete": "Supprimer",
  "pptx.undoAction.delete": "Supprimer",
  "pptx.common.delete": "Supprimer",
  "pptx.arrange.duplicate": "Dupliquer",
  "pptx.undoAction.duplicate": "Dupliquer",
  "pptx.accessibility.close": "Fermer",
  "pptx.headerFooter.close": "Fermer",
  "pptx.share.close": "Fermer",
  "pptx.settings.close": "Fermer",
  "pptx.selectionPane.close": "Fermer",
  "pptx.customShows.close": "Fermer",
  "pptx.themeEditor.close": "Fermer",
  "pptx.compare.close": "Fermer",
  "pptx.smartart.close": "Fermer",
  "pptx.encryptedFile.close": "Fermer",
  "pptx.mobileSheet.close": "Fermer",
  "pptx.common.close": "Fermer",
  "pptx.slideTemplates.close": "Fermer",
  "pptx.shortcuts.close": "Fermer",
  "pptx.ai.accept": "Appliquer",
  "pptx.hyperlinkDialog.apply": "Appliquer",
  "pptx.comments.cancel": "Annuler",
  "pptx.share.cancel": "Annuler",
  "pptx.export.cancel": "Annuler",
  "pptx.customShows.cancel": "Annuler",
  "pptx.common.cancel": "Annuler",
  "pptx.equation.cancel": "Annuler",
  "pptx.smartart.cancel": "Annuler",
  "pptx.hyperlinkDialog.cancel": "Annuler",
  "pptx.insertSmartArt.cancel": "Annuler",
  "pptx.slideTemplates.cancel": "Annuler",
  "pptx.titleBar.save": "Enregistrer",
  "pptx.comments.save": "Enregistrer",
  "pptx.customShows.save": "Enregistrer",
  "pptx.mobileMenu.save": "Enregistrer",
  "pptx.common.save": "Enregistrer",
  "pptx.options.save.label": "Enregistrer",
  "pptx.mobileMenu.open": "Ouvrir",
  "pptx.ole.open": "Ouvrir",
  "pptx.print.title": "Imprimer",
  "pptx.print.printButton": "Imprimer",
  "pptx.notes.print": "Imprimer",
  "pptx.mobileMenu.print": "Imprimer",
  "pptx.options.advanced.print": "Imprimer",
  "pptx.options.quickAccess.command.print": "Imprimer",
  "pptx.titleBar.search": "Rechercher",
  "pptx.textEffects.size": "Taille",
  "pptx.table.fontSize": "Taille",
  "pptx.effects.size": "Taille",
  "pptx.inspector.size": "Taille",
  "pptx.text3d.color": "Couleur",
  "pptx.textEffects.color": "Couleur",
  "pptx.effects.color": "Couleur",
  "pptx.fill.color": "Couleur",
  "pptx.print.color": "Couleur",
  "pptx.text3d.extrusionColor": "Couleur",
  "pptx.inspector.color": "Couleur",
  "pptx.print.colorColor": "Couleur",
  "pptx.options.printColorMode.color": "Couleur",
  "pptx.chart.titleColor": "Couleur",
  "pptx.image.washColor": "Couleur",
  "pptx.slideBackground.colour": "Couleur",
  "pptx.chart.bold": "Gras",
  "pptx.notes.bold": "Gras",
  "pptx.inspector.bold": "Gras",
  "pptx.notesToolbar.bold": "Gras",
  "pptx.format.bold": "Gras",
  "pptx.notes.italic": "Italique",
  "pptx.inspector.italic": "Italique",
  "pptx.notesToolbar.italic": "Italique",
  "pptx.format.italic": "Italique",
  "pptx.animation.catalogPreset.emph33": "Souligné",
  "pptx.notes.underline": "Souligné",
  "pptx.inspector.underline": "Souligné",
  "pptx.notesToolbar.underline": "Souligné",
  "pptx.format.underline": "Souligné",
};
